### ISSUE TITLE
OpenSSL certificate verify fails

### ISSUE THREAD

**Issue by dmatranga-bayer** [terrabrasilis/terrabrasilis_datasource#1] opened 2021-10-28 17:30 UTC
I installed the plugin via the QGIS repository, browsed to it via the Plugins menu > TerraBrasilis Data Source > TerraBrasilis Data Source > fails with error message.

Here is the error message I received:

``` diff
! 2021-10-28T12:21:59     WARNING Traceback (most recent call last):
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 456, in wrap_socket
              cnx.do_handshake()
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
              self._raise_ssl_error(self._ssl, result)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
              _raise_current_error()
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
              raise exception_type(errors)
             OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
              httplib_response = self._make_request(conn, method, url,
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connectionpool.py", line 343, in _make_request
              self._validate_conn(conn)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
              conn.connect()
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connection.py", line 337, in connect
              self.sock = ssl_wrap_socket(
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
              return context.wrap_socket(sock, server_hostname=server_hostname)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 462, in wrap_socket
              raise ssl.SSLError('bad handshake: %r' % e)
             ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
              resp = conn.urlopen(
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen
              retries = retries.increment(method, url, error=e, _pool=self,
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/util/retry.py", line 399, in increment
              raise MaxRetryError(_pool, url, error or ResponseError(cause))
             urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /terrabrasilis/terrabrasilis_datasource/master/data/geoserver_terrabrasilis_info.json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/Users/ekxin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/terrabrasilis_datasource/terrabrasilis_datasource.py", line 318, in run
              resp = requests.get(url_json)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/api.py", line 76, in get
              return request('get', url, params=params, **kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/api.py", line 61, in request
              return session.request(method=method, url=url, **kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
              resp = self.send(prep, **send_kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
              r = adapter.send(request, **kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
              raise SSLError(e, request=request)
             requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /terrabrasilis/terrabrasilis_datasource/master/data/geoserver_terrabrasilis_info.json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
             
```

**Comment by ammaciel** [comment] 2021-10-30 09:58
Hi  dmatranga-bayer,

Sorry, I am not familiar with package and library management on OSX. I installed this plugin in macOS Catalina virtual machine on Ubuntu 18.04 and worked without error using QGIS 3.16.12 Hannover. I can't reproduce this error here.


![Screenshot from 2021-10-30 06-30-42](https://user-images.githubusercontent.com/18755189/139528334-9bca0f34-3de5-4469-9ffa-fe5b29041689.png)


![Screenshot from 2021-10-30 06-32-30](https://user-images.githubusercontent.com/18755189/139528336-6b04dc64-866e-4a60-ab7a-5b6e6b7efc3a.png)


I saw into this blogpost: https://www.lutraconsulting.co.uk/blog/2020/10/01/qgis-macos-package/ that can give you a hint. 

Try follow these answers:  

- https://gis.stackexchange.com/questions/361545/how-do-i-specify-the-qgis-specific-python-version-to-add-python-packages-to-that
- https://github.com/Fatal1ty/aiofcm/issues/5
- https://github.com/qgis/QGIS-Mac-Packager/issues/32
- https://github.com/qgiscloud/qgis-cloud-plugin/wiki/Resolving-certificate-problems-on-OSX
- https://stackoverflow.com/questions/58272830/python-crashing-on-macos-10-15-beta-19a582a-with-usr-lib-libcrypto-dylib

Try to install python requests module, maybe it can resolve your issue. If the problem persists, open a new issue.

Grateful for the interest.

**Closed as completed** 2021-10-30 09:59 UTC
